[package]
name = "Julia_sets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
num = "0.4.1"
threadpool = "1.8.1"

[profile.release]
debug = true